### ISSUE TITLE
can't reproduce results with the model you provide

### ISSUE THREAD

**Issue by ZRJMoon** [Yuxin-CV/DTN#2]
Hi,
    I run the model you provide in folder DTN_SEED#5 and get accuracy only around 71%. Ps, I run 1*600 tasks when testing. But it should around 77% according your report.

**Comment by Yuxin-CV** [comment]
Can you provide your log?

**Comment by ZRJMoon** [comment]
> Can you provide your log?

load train dataset
48000
load test dataset
12000
==> Resuming from generator checkpoint..
test: 100 loss: 0.7847099539637565 acc: 71.54666851043702
test: 200 loss: 0.780451248139143 acc: 71.58000152587891
test: 300 loss: 0.7874181261658668 acc: 70.90666829427083
test: 400 loss: 0.7915166358649731 acc: 70.55000170707703
test: 500 loss: 0.7918601664304733 acc: 70.49600180053712
test: 600 loss: 0.7952163175741831 acc: 70.41777956644694
0 0.7952163175741831 70.41777956644694 0.6697213299215876

**Comment by Yuxin-CV** [comment]
> > Can you provide your log?
> 
> load train dataset
> 48000
> load test dataset
> 12000
> ==> Resuming from generator checkpoint..
> test: 100 loss: 0.7847099539637565 acc: 71.54666851043702
> test: 200 loss: 0.780451248139143 acc: 71.58000152587891
> test: 300 loss: 0.7874181261658668 acc: 70.90666829427083
> test: 400 loss: 0.7915166358649731 acc: 70.55000170707703
> test: 500 loss: 0.7918601664304733 acc: 70.49600180053712
> test: 600 loss: 0.7952163175741831 acc: 70.41777956644694
> 0 0.7952163175741831 70.41777956644694 0.6697213299215876

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/57927171/85258558-48595a00-b49a-11ea-8896-cbadad812a7c.png">

I run on my machine, it seems normal.

**Comment by Yuxin-CV** [comment]
Please check your code & dataset. @ZRJMoon
