### ISSUE TITLE
model parameters file

### ISSUE THREAD

**Issue by chengyu0910** [Yuxin-CV/DTN#3]
can you provide the the model parameters file reported in paper? thanks！

**Comment by Yuxin-CV** [comment]
Please check: https://github.com/Yuxin-CV/DTN/blob/491babb7e2a7dac65bff64ef30193fa34756fea2/main_DTN.py#L21-L51

**Comment by Yuxin-CV** [comment]
> Please check:
> 
> https://github.com/Yuxin-CV/DTN/blob/491babb7e2a7dac65bff64ef30193fa34756fea2/main_DTN.py#L21-L51

I believe I've answered your question and as such I'm closing this issue but let us know if you have any further questions.
